spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bouquinste?serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  resources:
    static-pa
  mvc:
    servlet:
      load-on-startup: 1
    static-path-pattern: /static/**

logging:
  level:
    com.re21.bouquiniste: debug
  file:
    path: src/main/resources/logs

mybatis:
  mapper-locations: static/mapper/*.xml
